# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Prepare Dependencies
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install build-essential git imagemagick libx11-dev libxext-dev libfreetype6-dev libpng-dev libjpeg-dev pkg-config gcc-arm-none-eabi binutils-arm-none-eabi
          git clone --recursive https://github.com/Lauryy06/Upsilon.git
          cd Upsilon
          git checkout upsilon-dev
      - name: Build n0100
        run: |
          make MODEL=n0100 clean
          make MODEL=n0100 EPSILON_I18N=fr OMEGA_USERNAME="" -j4
          make MODEL=n0100 OMEGA_USERNAME="" binpack -j4
      - name: Build n0110
        run: |
          make clean
          make OMEGA_USERNAME="" -j4
          make OMEGA_USERNAME="" binpack -j4
      - name: Web
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest-fastcomp
          ./emsdk activate latest-fastcomp
          source emsdk_env.sh
          cd ..
          make clean
          make PLATFORM=simulator TARGET=web OMEGA_USERNAME="" -j4
      - name: Infos
        run: ls
